on: [push]

name: AzureArmDeploySample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
      
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: deploy arm template
      id: deploy_rescgrp
      uses: mlopstemplates/arm_deploy@master
      with:
            scope: "subscription"
            template_file: "/.cloud/.azure/deploySub.json"
            location: "southcentralus"
          
    - name: Display deployment output details
      run: |
          echo deployment_status: "${{ steps.deploy_rescgrp.outputs.deployment_status}}"
          echo deployment_result: "${{ steps.deploy_rescgrp.outputs.deployment_result}}"
    - name: deploy arm template
      id: deploy_storage
      uses: mlopstemplates/arm_deploy@master
      with:
            scope: "resource_group"
            resource_group: "demo"
            template_file: "/.cloud/.azure/deploy.json"
            parameter_file: "/.cloud/.azure/deploy.params.json"
            parameters: "storageAccountName=demovivek01"
            
    - name: Display deployment output details
      run: |
          echo deployment_status: "${{ steps.deploy_storage.outputs.deployment_status}}"
          echo deployment_result: "${{ steps.deploy_storage.outputs.deployment_result}}"      
