name: arm-template-deploy
on: [push]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
         
    # Connect or Create the Azure Machine Learning Workspace
    - name: deploy all resources
      id: aml_configure
      uses: mlopstemplates/aml_configure@master
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          armtemplateparams_file: "deploy.params.json"
          armtemplate_file: "deploy.json"
          resource_group: ${{ secrets.RESOURCE_GROUP }}
          mapped_params: '{"storageAccountName":"amlconfiguretest"}'
          deployment_mode: "Incremental"
